const DASHBOARD_PAGE_HTML = `<!doctype html>
<html lang="th">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Nexus-DevFlow Blueprint Dashboard</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&family=Noto+Sans+Thai:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
  <style>
    :root{
      --font-display:"Google Sans Thai","Google Sans","Noto Sans Thai","Space Grotesk",sans-serif;
      --font-sans:"Google Sans Thai","Google Sans","Noto Sans Thai",sans-serif;
      --font-mono:"IBM Plex Mono",monospace;
      --bg:#0a2540;--bg-deep:#061a2e;--panel:rgba(255,255,255,.04);--panel-strong:#0c2b49;
      --ink:#edf6ff;--soft:#b7d3ef;--muted:#7598ba;--line:rgba(191,224,255,.17);--line-strong:rgba(191,224,255,.36);
      --cyan:#7dd8ff;--mint:#6fe3b4;--gold:#f2c14e;--red:#ff7061;--violet:#b8a4ff;
      --mint-soft:rgba(111,227,180,.14);--gold-soft:rgba(242,193,78,.14);--red-soft:rgba(255,112,97,.14);--violet-soft:rgba(184,164,255,.14);
    }
    *{box-sizing:border-box}
    html{color-scheme:dark}
    body{margin:0;min-height:100vh;background-color:var(--bg);color:var(--ink);font-family:var(--font-sans);-webkit-font-smoothing:antialiased;background-image:linear-gradient(rgba(125,216,255,.065) 1px,transparent 1px),linear-gradient(90deg,rgba(125,216,255,.065) 1px,transparent 1px),radial-gradient(circle at 8% -5%,rgba(125,216,255,.16),transparent 42rem);background-size:34px 34px,34px 34px,auto}
    button{font:inherit}
    code{font-family:var(--font-mono);color:var(--cyan)}
    .sheet{width:min(1180px,calc(100% - 40px));margin:0 auto;padding:34px 0 64px}
    .titleblock{display:flex;align-items:flex-end;justify-content:space-between;gap:26px;padding-bottom:20px;border-bottom:1px solid var(--line-strong);flex-wrap:wrap}
    .eyebrow,.label{font:600 10px/1 var(--font-mono);letter-spacing:.13em;text-transform:uppercase;color:var(--cyan)}
    .eyebrow{display:flex;align-items:center;gap:8px;margin-bottom:12px}.eyebrow:before{content:"";width:20px;height:1px;background:var(--cyan)}
    h1{margin:0 0 6px;font:700 clamp(32px,4vw,48px)/1.05 var(--font-display);letter-spacing:-.03em}
    .path,.muted{color:var(--muted);font-size:12px;line-height:1.65}.path{font-family:var(--font-mono)}
    .badges{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.badge,.pill{padding:4px 9px;border:1px solid var(--line-strong);border-radius:3px;background:rgba(255,255,255,.025);color:var(--muted);font:600 10px/1.5 var(--font-mono);text-transform:uppercase}
    .ok,.healthy,.current,.ready,.idle{border-color:rgba(111,227,180,.42)!important;color:var(--mint)!important;background:var(--mint-soft)!important}
    .warning,.available,.offline,.blocked,.fail{border-color:rgba(255,112,97,.42)!important;color:var(--red)!important;background:var(--red-soft)!important}
    .active,.deep,.fast,.configured{border-color:rgba(184,164,255,.42)!important;color:var(--violet)!important;background:var(--violet-soft)!important}
    .meta{display:grid;grid-template-columns:auto auto;gap:4px 20px;margin:0;font:11px/1.55 var(--font-mono)}.meta dt{color:var(--muted);text-transform:uppercase}.meta dd{margin:0;color:var(--soft);text-align:right}
    .live{display:flex;align-items:center;gap:8px;margin:14px 0 24px;font:11px var(--font-mono);color:var(--muted)}.live-dot{width:7px;height:7px;border-radius:50%;background:var(--gold)}.live-dot.on{background:var(--mint);box-shadow:0 0 0 4px rgba(111,227,180,.12)}
    .panel,.card{position:relative;min-width:0;border:1px solid var(--line);border-radius:4px;background:var(--panel)}
    #dual-track{overflow:hidden}
    .stepper{justify-content:center}.step{display:flex;flex-direction:column;align-items:center;text-align:center}.step-icon{display:grid;place-items:center;width:30px;height:30px;margin:10px auto 8px;border:1px solid currentColor;border-radius:8px;background:rgba(255,255,255,.035)}.icon-glyph{display:block;font-size:17px;line-height:1}.step.flow-0,.step.flow-4{color:var(--cyan)}.step.flow-1,.step.flow-5{color:var(--violet)}.step.flow-2,.step.flow-6{color:var(--gold)}.step.flow-3,.step.flow-7{color:var(--mint)}.step .step-name{color:currentColor}.step .step-cmd{color:var(--muted)}
    .panel{padding:24px 26px;margin-bottom:20px}.panel-head,.card-head{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.panel-head{margin-bottom:20px}.card-head{margin-bottom:17px}
    .track-tabs{display:flex;gap:7px}.tab{padding:7px 13px;border:1px solid var(--line-strong);border-radius:99px;background:transparent;color:var(--muted);font:600 10px var(--font-mono);cursor:pointer}.tab:hover,.tab:focus-visible{border-color:var(--cyan);color:var(--cyan);outline:none}.tab.on{background:var(--cyan);border-color:var(--cyan);color:var(--bg-deep)}
    .track-view{display:none;min-width:0}.track-view.on{display:block}.stepper{display:flex;width:100%;max-width:100%;overflow-x:auto;padding:4px 0 7px}.step{flex:1 1 0;min-width:104px;position:relative;padding-right:12px}.step-line{position:absolute;top:10px;left:21px;right:0;height:1px;background:var(--line-strong)}.step:last-child .step-line{display:none}.step.done .step-line{background:var(--mint)}
    .step-dot{position:relative;z-index:1;width:21px;height:21px;border-radius:50%;display:grid;place-items:center;border:2px solid var(--line-strong);background:var(--bg-deep);color:var(--muted);font:700 8px var(--font-mono)}.step.done .step-dot{border-color:var(--mint);color:var(--mint)}.step.active .step-dot{border-color:var(--gold);color:var(--gold);box-shadow:0 0 0 4px rgba(242,193,78,.16)}
    .step-name{margin-top:9px;color:var(--soft);font:600 10px/1.35 var(--font-mono)}.step.active .step-name{color:var(--gold)}.step.done .step-name{color:var(--mint)}.step-cmd{margin-top:3px;color:var(--muted);font:9px/1.4 var(--font-mono)}.track-note{margin-top:12px;padding-top:12px;border-top:1px dashed var(--line);color:var(--muted);font:11px/1.65 var(--font-mono)}
    .next-action{background:var(--bg-deep);border-color:var(--line-strong)}.next-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.command{margin:8px 0 6px;color:var(--gold);font:700 clamp(22px,3vw,30px)/1.3 var(--font-mono)}.copy{padding:7px 12px;border:1px solid var(--cyan);border-radius:3px;background:transparent;color:var(--cyan);font:600 10px var(--font-mono);cursor:pointer}.copy:hover,.copy:focus-visible{background:var(--cyan);color:var(--bg-deep);outline:none}
    .stats{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;margin:0 0 20px;border:1px solid var(--line);border-radius:4px;overflow:hidden;background:var(--line)}.stat{padding:16px 18px;background:var(--bg-deep)}.stat-value{font:700 25px/1 var(--font-display)}.stat-label{margin-top:6px;color:var(--muted);font:10px var(--font-mono);text-transform:uppercase;letter-spacing:.08em}
    .grid{display:grid;grid-template-columns:repeat(12,1fr);gap:20px;margin-bottom:20px}.card{grid-column:span 4;min-width:0;padding:clamp(20px,2.4vw,28px)}.card.wide{grid-column:span 8}.card.full{grid-column:1/-1}.value{font:700 18px/1.4 var(--font-display)}
    .facts{display:grid;gap:10px}.fact{display:flex;justify-content:space-between;gap:16px;padding-bottom:10px;border-bottom:1px dashed var(--line)}.fact:last-child{padding-bottom:0;border:0}.fact span:first-child{color:var(--muted);font-size:11px}.fact span:last-child{color:var(--soft);font:11px var(--font-mono);text-align:right;overflow-wrap:anywhere}
    .progress{height:6px;margin:14px 0 9px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.progress span{display:block;height:100%;width:0;background:var(--gold);transition:width .35s ease}
    ul{list-style:none;margin:0;padding:0}li{padding:10px 0;border-bottom:1px dashed var(--line);color:var(--soft);font-size:12px;line-height:1.55}li:last-child{border:0}.empty{color:var(--muted)}
    .severity{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.sev{padding:9px 6px;border:1px solid var(--line);border-radius:3px;text-align:center}.sev b{display:block;font:700 17px var(--font-display)}.sev small{color:var(--muted);font:9px var(--font-mono)}
    .commands{display:flex;flex-wrap:wrap;gap:10px}.cmd{position:relative;padding:8px 13px;border:1px solid var(--line-strong);border-radius:3px;background:rgba(255,255,255,.025);color:var(--soft);font:11px var(--font-mono);cursor:pointer}.cmd:hover,.cmd:focus-visible,.cmd:focus{border-color:var(--cyan);color:var(--cyan);outline:2px solid rgba(125,216,255,.2);outline-offset:2px}.cmd:after{content:attr(data-tip);position:absolute;z-index:30;left:50%;bottom:calc(100% + 10px);width:max-content;max-width:min(300px,80vw);padding:9px 11px;border:1px solid var(--line-strong);border-radius:3px;background:#031421;color:var(--soft);font:10px/1.5 var(--font-mono);white-space:normal;text-align:left;opacity:0;visibility:hidden;transform:translate(-50%,5px);box-shadow:0 12px 30px rgba(0,0,0,.4);transition:.15s;pointer-events:none}.cmd:hover:after,.cmd:focus-visible:after,.cmd:focus:after{opacity:1;visibility:visible;transform:translate(-50%,0)}
    .adapters{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.adapter{padding:15px;border:1px solid var(--line);border-radius:3px;background:rgba(255,255,255,.02)}.adapter strong{display:block;margin-bottom:6px;text-transform:capitalize}.adapter-path{color:var(--muted);font:10px var(--font-mono)}.adapter-state{margin-top:9px;font:10px var(--font-mono)}
    .idea-meta,.history-meta{margin-top:4px;color:var(--muted);font:10px var(--font-mono)}
    .section-note{margin:-2px 0 14px;color:var(--muted);font:10px/1.5 var(--font-mono)}.record-list{display:grid;gap:8px}.record-item{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:13px;align-items:center;padding:13px 15px;border:1px solid var(--line);border-left:3px solid var(--record-color,var(--cyan));border-radius:3px;background:rgba(255,255,255,.02)}.record-icon{display:grid;place-items:center;width:31px;height:31px;border-radius:8px;background:color-mix(in srgb,var(--record-color,var(--cyan)) 14%,transparent)}.record-body{min-width:0}.record-meta{color:var(--record-color,var(--cyan));font:700 10px var(--font-mono);letter-spacing:.06em;text-transform:uppercase}.record-title{margin-top:3px;color:var(--ink);font-weight:650}.record-desc{margin-top:3px;color:var(--soft);font-size:12px}.record-desc:empty{display:none}.record-title strong,.record-desc strong{color:var(--record-color,var(--cyan));font-weight:750}.record-title em,.record-desc em{color:var(--gold)}.record-title code,.record-desc code{padding:1px 4px;border:1px solid var(--line);border-radius:3px;color:var(--cyan);font:10px var(--font-mono)}.record-title a,.record-desc a{color:var(--cyan);text-decoration:underline}.record-actions{display:flex;align-items:center;justify-content:flex-end;gap:7px;flex-wrap:wrap}.record-action{border:1px solid var(--record-color,var(--cyan));border-radius:3px;padding:8px 11px;background:transparent;color:var(--record-color,var(--cyan));font:700 10px var(--font-mono);cursor:pointer}.record-action:hover,.record-action:focus-visible{background:var(--record-color,var(--cyan));color:var(--bg)}.record-badge{align-self:start;border:1px solid rgba(111,227,180,.36);border-radius:99px;padding:4px 8px;background:var(--mint-soft);color:var(--mint);font:700 9px var(--font-mono);letter-spacing:.04em;text-transform:uppercase}.record-item.tone-cyan{--record-color:var(--cyan)}.record-item.tone-mint{--record-color:var(--mint)}.record-item.tone-gold{--record-color:var(--gold)}.record-item.tone-red{--record-color:var(--red)}.record-item.tone-violet{--record-color:var(--violet)}.stepper{gap:0;justify-content:center}.step{padding-right:0;overflow:visible}.step-line{left:calc(50% + 10px);right:calc(-50% + 10px);width:auto}#sev-p0{color:var(--red)}#sev-p1{color:var(--gold)}#sev-p2{color:var(--violet)}#sev-p3{color:var(--cyan)}#stat-runs.tone{color:var(--mint)}#stat-findings.tone-ok{color:var(--mint)}#stat-findings.tone-alert{color:var(--red)}#stat-ideas.tone-ok{color:var(--mint)}#stat-ideas.tone-pending{color:var(--gold)}#stat-adapters.tone-ok{color:var(--mint)}#stat-adapters.tone-partial{color:var(--gold)}#stat-state.tone-idle{color:var(--cyan)}#stat-state.tone-active{color:var(--violet)}#stat-state.tone-blocked{color:var(--red)}
    footer{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:26px;padding-top:17px;border-top:1px solid var(--line);color:var(--muted);font:10px var(--font-mono)}
    @media(max-width:920px){.grid .card,.grid .card.wide{grid-column:1/-1}.stats{grid-template-columns:repeat(2,1fr)}.adapters{grid-template-columns:repeat(2,1fr)}.titleblock{align-items:flex-start;flex-direction:column}.meta dd{text-align:left}.stepper{gap:0}.cmd:after{position:fixed;left:12px;right:12px;bottom:16px;width:auto;max-width:none;transform:translateY(5px)}.cmd:hover:after,.cmd:focus-visible:after,.cmd:focus:after{transform:none}}
    @media(max-width:560px){.sheet{width:calc(100% - 24px);padding-top:22px}.panel,.card{padding:18px}.grid{gap:14px;margin-bottom:14px}.stats{margin-bottom:14px}.adapters{grid-template-columns:1fr}.cmd:after{position:fixed;left:12px;right:12px;bottom:16px;width:auto;max-width:none;transform:translateY(5px)}.cmd:hover:after,.cmd:focus-visible:after,.cmd:focus:after{transform:none}.meta{grid-template-columns:1fr}.track-tabs{width:100%}.tab{flex:1}.fact{align-items:flex-start}.record-item{grid-template-columns:34px minmax(0,1fr)}.record-action{grid-column:2;justify-self:start}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;transition-duration:.001ms!important}}
  </style>
</head>
<body>
  <main class="sheet">
    <header class="titleblock">
      <div><div class="eyebrow">Nexus-DevFlow · Workspace Status</div><h1 id="project-name">Nexus-DevFlow</h1><div class="path" id="project-path">Connecting...</div><div class="badges"><span class="badge" id="version-badge">version</span><span class="badge" id="health-badge">health</span><span class="badge">MIT</span><span class="badge" id="track-badge">track</span></div></div>
      <dl class="meta"><dt>Package</dt><dd id="package-name">@jakkrichm/create-nexus-devflow</dd><dt>Adapters</dt><dd id="adapter-count">-</dd><dt>Branch</dt><dd id="header-branch">-</dd><dt>Snapshot</dt><dd id="generated-at">-</dd></dl>
    </header>
    <div class="live"><span class="live-dot" id="live-dot"></span><span id="live-label">Connecting to local dashboard...</span></div>

    <section class="panel" id="dual-track">
      <div class="panel-head"><span class="label">Dual-Track Delivery Model</span><div class="track-tabs" role="tablist" aria-label="Delivery tracks"><button class="tab on" id="tab-fast" role="tab" aria-selected="true" aria-controls="view-fast" data-track="fast">🚀 Fast-Track · 4 steps</button><button class="tab" id="tab-deep" role="tab" aria-selected="false" aria-controls="view-deep" data-track="deep">♟️ Deep-Track · 8 stages</button></div></div>
      <div class="track-view on" id="view-fast" role="tabpanel" aria-labelledby="tab-fast"><div class="stepper" id="pipeline-fast"></div><div class="track-note" id="note-fast">Fast-Track for daily features, fixes, UI work and iterative refactoring.</div></div>
      <div class="track-view" id="view-deep" role="tabpanel" aria-labelledby="tab-deep"><div class="stepper" id="pipeline-deep"></div><div class="track-note" id="note-deep">Deep-Track for architecture, migrations, security audits and coordinated delivery.</div></div>
    </section>

    <section class="panel next-action" id="next-panel">
      <div class="next-head"><span class="label">Next Action</span><button class="copy" id="next-copy" type="button">Copy command</button></div><div class="command" id="next-command" aria-live="polite">Loading...</div><div class="muted" id="next-reason"></div>
    </section>

    <section class="stats" aria-label="Workspace summary"><div class="stat"><div class="stat-value" id="stat-runs">-</div><div class="stat-label">Runs released</div></div><div class="stat"><div class="stat-value" id="stat-findings">-</div><div class="stat-label">Active findings</div></div><div class="stat"><div class="stat-value" id="stat-ideas">-</div><div class="stat-label">Pending ideas</div></div><div class="stat"><div class="stat-value" id="stat-adapters">-</div><div class="stat-label">Adapters configured</div></div><div class="stat"><div class="stat-value" id="stat-state">-</div><div class="stat-label">Current state</div></div></section>

    <section class="grid">
      <article class="card"><div class="card-head"><span class="label">Nexus-DevFlow</span><span class="pill" id="update-pill">checking</span></div><div class="facts"><div class="fact"><span>Installed / latest</span><span id="installed-latest">-</span></div><div class="fact"><span>Health</span><span id="system-health">-</span></div><div class="fact"><span>Architecture</span><span>3-Pillars + Dual-Track</span></div></div></article>
      <article class="card wide"><div class="card-head"><span class="label">Current Work</span><span class="pill" id="work-pill">loading</span></div><div class="value" id="work-title">Loading...</div><div class="progress"><span id="work-progress"></span></div><div class="muted" id="work-meta"></div></article>
      <article class="card"><div class="card-head"><span class="label">Git Status</span><span class="pill" id="git-pill">loading</span></div><div class="facts"><div class="fact"><span>Branch</span><span id="git-branch">-</span></div><div class="fact"><span>Working tree</span><span id="git-changed">-</span></div><div class="fact"><span>Upstream</span><span id="git-upstream">-</span></div><div class="fact"><span>Last commit</span><span id="git-commit">-</span></div></div></article>
      <article class="card"><div class="card-head"><span class="label">Findings Ledger</span><span class="value" id="findings-count">-</span></div><div class="severity"><div class="sev"><b id="sev-p0">0</b><small>P0</small></div><div class="sev"><b id="sev-p1">0</b><small>P1</small></div><div class="sev"><b id="sev-p2">0</b><small>P2</small></div><div class="sev"><b id="sev-p3">0</b><small>P3</small></div></div><ul id="findings-list"></ul></article>
      <article class="card"><div class="card-head"><span class="label">Completion</span><span class="pill" id="completion-pill">-</span></div><ul id="completion-list"></ul></article>
      <article class="card"><div class="card-head"><span class="label">Warnings</span><span class="value" id="warnings-count">-</span></div><ul id="warnings-list"></ul></article>
    </section>

    <section class="grid"><article class="card full"><div class="card-head"><span class="label">Doctor · Health Check</span><span class="pill" id="doctor-pill">-</span></div><div class="record-list" id="doctor-list"></div></article></section>
    <section class="card full panel"><div class="card-head"><span class="label">Discoveries</span><span class="value" id="discovery-count">-</span></div><div class="record-list" id="discovery-list"></div></section>
    <section class="card full panel"><div class="card-head"><span class="label">Quick Commands</span><span class="muted">hover or focus for help · click to copy</span></div><div class="commands" id="command-list"></div></section>
    <section class="card full panel"><div class="card-head"><span class="label">Adapter Health</span><span class="muted">configured · detected · healthy</span></div><div class="adapters" id="adapter-list"></div></section>
    <section class="card full panel"><div class="card-head"><span class="label">Idea Inbox & Backlog</span><span class="value" id="ideas-count">-</span></div><div class="section-note">From devflow/ideas.md · start a selected item with /feature IDEA-xxx</div><div class="record-list" id="ideas-list"></div></section>
    <section class="card full panel"><div class="card-head"><span class="label">Completed Work Archive</span><span class="value" id="history-count">-</span></div><div class="section-note">Categorized delivery history · features, fixes and rollbacks</div><div class="record-list" id="history-list"></div></section>
    <footer><span>Read-only local DevFlow 2.0 dashboard · refreshes every 2 seconds</span><span id="footer-revision">snapshot pending</span></footer>
  </main>
  <script>
    const byId = (id) => document.getElementById(id);
    const text = (id, value) => { const node = byId(id); if (node) node.textContent = value == null ? '-' : String(value); };
    const pill = (id, state, label) => { const node = byId(id); if (!node) return; node.className = 'pill ' + (state || 'configured'); node.textContent = label || state || '-'; };
    const list = (id, values, empty) => { const node = byId(id); if (!node) return; node.replaceChildren(); const rows = values.length ? values : [empty]; rows.forEach((value) => { const li = document.createElement('li'); li.textContent = value; if (!values.length) li.className = 'empty'; node.append(li); }); };
    const titleCase = (value) => String(value || '').replaceAll('_',' ').replace(/\b\w/g, (c) => c.toUpperCase());
    const ICON_PATHS = { compass:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7z', target:'M12 3a9 9 0 1 0 9 9M12 7a5 5 0 1 0 5 5M12 10a2 2 0 1 0 2 2', document:'M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6', list:'M8 6h12M8 12h12M8 18h12M3 6h1M3 12h1M3 18h1', code:'M8 8l-4 4 4 4M16 8l4 4-4 4M14 4l-4 16', shield:'M12 2l8 3v6c0 5-3 9-8 11-5-2-8-6-8-11V5zM8 12l3 3 5-6', report:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5', package:'M3 7l9-5 9 5v10l-9 5-9-5zM3 7l9 5 9-5M12 12v10', bulb:'M9 18h6M10 22h4M8 14c-2-1-3-3-3-5a7 7 0 0 1 14 0c0 2-1 4-3 5-1 1-1 2-1 3H9c0-1 0-2-1-3z', check:'M5 12l4 4L19 6', wrench:'M14 6a4 4 0 0 0-5 5L3 17l4 4 6-6a4 4 0 0 0 5-5l-3 1-2-2 1-3z', rollback:'M9 7H4v-5M4 7a9 9 0 1 1-1 7', search:'M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14M16 16l5 5', alert:'M12 3l10 18H2zM12 9v5M12 18h.01' };
    const FLOW_ICON_NAMES = ['compass','target','document','list','code','shield','report','package'];
    const EMOJI_ICONS = { compass:'🔎',target:'🎯',document:'📄',list:'🧩',code:'⚙️',shield:'🛡️',report:'📊',package:'📦',bulb:'⚡',check:'✅',wrench:'🛠️',rollback:'↩️',search:'🔍',alert:'⚠️' };
    function iconImage(name) { const icon = document.createElement('span'); icon.className = 'icon-glyph'; icon.setAttribute('aria-hidden','true'); icon.textContent = EMOJI_ICONS[name] || '📄'; return icon; }
    function decoratePipeline(id) { byId(id)?.querySelectorAll('.step').forEach((step,index) => { step.classList.add('flow-' + index); const icon = document.createElement('span'); icon.className = 'step-icon'; icon.setAttribute('aria-hidden','true'); icon.append(iconImage(FLOW_ICON_NAMES[index] || 'document')); const name = step.querySelector('.step-name'); step.insertBefore(icon,name || null); }); }
    function richText(root,value) { const source = String(value || ''); let cursor = 0; const plain = (end) => { if (end > cursor) root.append(document.createTextNode(source.slice(cursor,end))); cursor = end; }; while (cursor < source.length) { if (source.startsWith('**',cursor)) { const end = source.indexOf('**',cursor + 2); if (end > cursor + 2) { const node = document.createElement('strong'); node.textContent = source.slice(cursor + 2,end); root.append(node); cursor = end + 2; continue; } } if (source[cursor] === '*') { const end = source.indexOf('*',cursor + 1); if (end > cursor + 1) { const node = document.createElement('em'); node.textContent = source.slice(cursor + 1,end); root.append(node); cursor = end + 1; continue; } } if (source.charCodeAt(cursor) === 96) { const end = source.indexOf(String.fromCharCode(96),cursor + 1); if (end > cursor + 1) { const node = document.createElement('code'); node.textContent = source.slice(cursor + 1,end); root.append(node); cursor = end + 1; continue; } } if (source[cursor] === '[') { const close = source.indexOf('](',cursor + 1); const end = close >= 0 ? source.indexOf(')',close + 2) : -1; const href = close >= 0 && end > close ? source.slice(close + 2,end) : ''; if (close > cursor + 1 && end > close && (href.startsWith('https://') || href.startsWith('http://'))) { const node = document.createElement('a'); node.textContent = source.slice(cursor + 1,close); node.href = href; node.target = '_blank'; node.rel = 'noreferrer'; root.append(node); cursor = end + 1; continue; } } const next = [source.indexOf('**',cursor + 1),source.indexOf('*',cursor + 1),source.indexOf(String.fromCharCode(96),cursor + 1),source.indexOf('[',cursor + 1)].filter((index) => index >= 0).sort((a,b) => a-b)[0] ?? source.length; plain(next > cursor ? next : cursor + 1); } }
    function recordCard(options) { const card = document.createElement('article'); card.className = 'record-item tone-' + (options.tone || 'cyan'); const icon = document.createElement('span'); icon.className = 'record-icon'; icon.append(iconImage(options.icon || 'document')); const body = document.createElement('div'); body.className = 'record-body'; const meta = document.createElement('div'); meta.className = 'record-meta'; richText(meta,options.meta); const title = document.createElement('div'); title.className = 'record-title'; richText(title,options.title); const desc = document.createElement('div'); desc.className = 'record-desc'; richText(desc,options.description); body.append(meta,title,desc); card.append(icon,body); if (options.badge) { const badge = document.createElement('span'); badge.className = 'record-badge'; badge.textContent = options.badge; card.append(badge); } else if (options.actions?.length) { const actions = document.createElement('div'); actions.className = 'record-actions'; options.actions.forEach((command) => { const action = document.createElement('button'); action.className = 'record-action'; action.type = 'button'; action.textContent = command; action.addEventListener('click',() => { navigator.clipboard?.writeText(command); action.textContent = 'Copied'; setTimeout(() => { action.textContent = command; },1200); }); actions.append(action); }); card.append(actions); } return card; }
    function renderRecords(id,items,empty,mapper) { const root = byId(id); root.replaceChildren(); if (!items?.length) { const node = document.createElement('div'); node.className = 'empty'; node.textContent = empty; root.append(node); return; } items.forEach((item,index) => root.append(recordCard(mapper(item,index)))); }
    function ideaTone(feasibility) { const value = String(feasibility || '').toLowerCase(); if (value.includes('high') || value.includes('easy') || value.includes('ง่าย')) return 'mint'; if (value.includes('low') || value.includes('hard') || value.includes('ยาก')) return 'red'; if (value.includes('medium') || value.includes('ปานกลาง')) return 'gold'; return 'violet'; }
    function renderIdeas(items) { renderRecords('ideas-list',items,'No pending ideas',(item) => ({ icon:'bulb',tone:ideaTone(item.feasibility),meta:item.id,title:item.title,description:(item.description || '⚡') + ' · ' + (item.feasibility || '**Not scored**'),actions:['/feature ' + item.id,'/discovery ' + item.id] })); }
    function renderHistory(items) { const map = { feature:{icon:'package',tone:'cyan'},fix:{icon:'wrench',tone:'gold'},rollback:{icon:'rollback',tone:'red'} }; renderRecords('history-list',(items || []).slice(0,10),'No completed work in history archive',(item) => { const type = String(item.type || 'other').toLowerCase(); const style = map[type] || {icon:'report',tone:'violet'}; return { ...style,meta:type + ' ' + (item.buildPlanItem || ''),title:item.title,description:'',badge:'Released' }; }); }
    function renderDoctor(items) { renderRecords('doctor-list',items,'No doctor checks available',(item) => ({ icon:item.status === 'pass' ? 'check' : 'alert',tone:item.status === 'pass' ? 'mint' : item.status === 'warn' ? 'gold' : 'red',meta:item.status,title:item.name,description:item.message })); }
    function renderDiscoveries(items) { renderRecords('discovery-list',items,'No discoveries recorded',(item) => { const decision = item.decision || 'Pending'; const normalized = String(decision).toLowerCase(); return { icon:'search',tone:normalized === 'proceed' || normalized === 'approved' ? 'mint' : 'violet',meta:item.id,title:item.title,description:'',badge:'Decision: ' + decision }; }); }
    let nextCopyValue = '/feature';
    let nextCopyLabel = '/feature';
    byId('next-copy').addEventListener('click',(event) => { event.stopImmediatePropagation(); navigator.clipboard?.writeText(nextCopyValue); const button = byId('next-copy'); button.textContent = 'Copied ' + nextCopyLabel; setTimeout(() => { button.textContent = 'Copy command ' + nextCopyLabel; },1200); },true);
    let preferredTrack = (() => { try { return localStorage.getItem('devflow-dashboard-track'); } catch { return null; } })();
    document.querySelectorAll('[data-track]').forEach((button) => button.addEventListener('click',() => { preferredTrack = button.dataset.track; try { localStorage.setItem('devflow-dashboard-track',preferredTrack); } catch {} },{capture:true}));

    function renderPipeline(id, nodes) {
      const root = byId(id); root.replaceChildren();
      (nodes || []).forEach((node, index) => {
        const step = document.createElement('div'); step.className = 'step ' + node.state;
        const line = document.createElement('span'); line.className = 'step-line';
        const dot = document.createElement('span'); dot.className = 'step-dot'; dot.textContent = node.state === 'done' ? '✓' : String(index + 1).padStart(nodes.length > 4 ? 2 : 1, '0');
        const name = document.createElement('div'); name.className = 'step-name'; name.textContent = node.label;
        const command = document.createElement('div'); command.className = 'step-cmd'; command.textContent = node.command;
        step.append(line, dot, name, command); root.append(step);
      });
    }

    function selectTrack(track) {
      document.querySelectorAll('.tab').forEach((node) => { const on = node.dataset.track === track; node.classList.toggle('on', on); node.setAttribute('aria-selected', String(on)); });
      document.querySelectorAll('.track-view').forEach((node) => node.classList.toggle('on', node.id === 'view-' + track));
    }

    function wireCopy(button, getValue) {
      button.addEventListener('click', async () => {
        const original = button.textContent;
        button.textContent = 'Copied!';
        try { await navigator.clipboard.writeText(getValue()); }
        catch { button.textContent = 'Copy unavailable'; }
        setTimeout(() => { button.textContent = original; }, 1100);
      });
    }

    document.querySelectorAll('.tab').forEach((node) => node.addEventListener('click', () => selectTrack(node.dataset.track)));
    wireCopy(byId('next-copy'), () => byId('next-command').textContent.trim());

    function renderCommands(commands) {
      const root = byId('command-list'); root.replaceChildren();
      (commands || []).filter((item) => item.family === 'companion').forEach((item) => {
        const button = document.createElement('button'); button.type = 'button'; button.className = 'cmd'; button.textContent = item.name; button.dataset.tip = item.description; button.setAttribute('aria-label', item.name + ': ' + item.description); wireCopy(button, () => item.command); root.append(button);
      });
    }

    function renderAdapters(adapters) {
      const root = byId('adapter-list'); root.replaceChildren();
      (adapters || []).forEach((item) => { const card = document.createElement('div'); card.className = 'adapter'; const name = document.createElement('strong'); name.textContent = item.name; const path = document.createElement('div'); path.className = 'adapter-path'; path.textContent = item.path; const state = document.createElement('div'); state.className = 'adapter-state ' + item.state; state.textContent = item.state + ' · ' + item.message; card.append(name,path,state); root.append(card); });
    }

    function renderSnapshot(data) {
      const status = data.status || {}; const project = status.project || {}; const devflow = status.devflow || {}; const work = status.currentWork || {}; const git = status.git || {}; const findings = status.findings || { active: [], blockers: [] }; const workflow = data.workflow || {}; const update = data.update || {}; const doctor = data.doctor || { checks: [] }; const discoveries = data.discoveries || { recent: [] }; const history = data.history || { items: [], total: 0 }; const ideas = status.ideas || { pending: [], totalPending: 0 };
      text('project-name', project.name || 'Nexus-DevFlow'); text('project-path', project.root || ''); text('version-badge', 'v' + (devflow.version || 'unknown')); pill('health-badge', status.health, status.health === 'ok' ? 'Health OK' : 'Health warning'); pill('track-badge', workflow.track, 'Track ' + titleCase(workflow.track || 'idle'));
      text('adapter-count', (devflow.adapters || []).length + ' configured'); text('header-branch', git.branch || 'unknown'); text('generated-at', new Date(data.generatedAt).toLocaleTimeString()); text('footer-revision', 'snapshot ' + data.generatedAt);
      renderPipeline('pipeline-fast', workflow.fast); renderPipeline('pipeline-deep', workflow.deep); decoratePipeline('pipeline-fast'); decoratePipeline('pipeline-deep'); selectTrack(preferredTrack || (workflow.track === 'deep' ? 'deep' : 'fast'));
      text('note-fast', workflow.track === 'fast' ? 'Active Fast-Track run: ' + (work.runId || work.title || 'current work') : 'Fast-Track is ready for daily features, fixes, UI work and iterative refactoring.');
      text('note-deep', workflow.track === 'deep' ? 'Active Deep-Track run: ' + (workflow.activeRunId || workflow.activeDiscoveryId || 'current run') + ' · stage ' + (workflow.currentStage || 'unknown') : 'Deep-Track is ready for architecture, migrations, security audits and coordinated delivery.');
      const nextCommand = data.nextAction?.command || status.nextAction?.command || '/feature'; const workTitle = String(work.title || ''); const bracketStart = workTitle.indexOf('['); const bracketEnd = bracketStart >= 0 ? workTitle.indexOf(']',bracketStart + 1) : -1; const titleRunId = bracketStart >= 0 && bracketEnd > bracketStart ? workTitle.slice(bracketStart + 1,bracketEnd).trim() : ''; const nextRunId = work.runId || work.id || workflow.activeRunId || workflow.activeDiscoveryId || titleRunId; nextCopyValue = nextRunId ? nextCommand + ' ' + nextRunId : nextCommand; nextCopyLabel = nextCommand; text('next-command', nextCommand); text('next-copy', 'Copy command ' + nextCopyLabel); byId('next-copy').title = 'Copy ' + nextCopyValue; text('next-reason', data.nextAction?.reason || status.nextAction?.reason || 'Ready for new work.');
      text('stat-runs', history.total || 0); const activeFindings = (findings.active || []).length; text('stat-findings', activeFindings); text('stat-ideas', ideas.totalPending || 0); const healthyAdapters = (data.adapters || []).filter((item) => item.state === 'configured' || item.state === 'detected' || item.state === 'healthy').length; text('stat-adapters', healthyAdapters + '/' + (devflow.adapters || []).length); text('stat-state', titleCase(work.state || 'idle')); byId('stat-runs').className = 'stat-value tone'; byId('stat-findings').className = 'stat-value ' + (activeFindings ? 'tone-alert' : 'tone-ok'); byId('stat-ideas').className = 'stat-value ' + (ideas.totalPending ? 'tone-pending' : 'tone-ok'); byId('stat-adapters').className = 'stat-value ' + (healthyAdapters === (devflow.adapters || []).length ? 'tone-ok' : 'tone-partial'); byId('stat-state').className = 'stat-value tone-' + (work.state === 'blocked' ? 'blocked' : work.state === 'active' ? 'active' : 'idle');
      pill('update-pill', update.state, update.state === 'current' ? 'up to date' : update.state); text('installed-latest', (update.installedVersion || 'unknown') + ' / ' + (update.latestVersion || update.state)); text('system-health', status.health || 'unknown');
      pill('work-pill', work.state, work.state || 'idle'); text('work-title', work.title || 'No active delivery run'); const pct = work.total > 0 ? Math.round((work.completed / work.total) * 100) : 0; byId('work-progress').style.width = pct + '%'; text('work-meta', work.state === 'active' ? work.completed + ' of ' + work.total + ' steps completed' : 'Last completed: ' + (workflow.lastCompletedRun || 'none recorded'));
      pill('git-pill', git.clean ? 'ok' : 'warning', git.clean ? 'clean' : (git.changedFiles || 0) + ' changed'); text('git-branch', git.branch || 'unknown'); text('git-changed', git.clean ? 'clean' : (git.changedFiles || 0) + ' changed files'); text('git-upstream', git.upstream ? git.upstream + ' · ' + (git.ahead || 0) + ' ahead / ' + (git.behind || 0) + ' behind' : 'none'); text('git-commit', git.lastCommit || '-');
      text('findings-count', findings.total || 0); ['P0','P1','P2','P3'].forEach((severity) => text('sev-' + severity.toLowerCase(), (findings.active || []).filter((item) => item.severity === severity).length)); list('findings-list', (findings.active || []).map((item) => item.id + ' · ' + item.title), 'No active findings');
      pill('completion-pill', status.completion?.state, status.completion?.state || 'unknown'); list('completion-list', status.completion?.blockers || [], work.state === 'idle' ? 'No active run to complete' : 'All readiness checks passed'); text('warnings-count', (status.warnings || []).length); list('warnings-list', (status.warnings || []).map((item) => item.message), 'No active warnings or drift');
      pill('doctor-pill', doctor.failCount ? 'fail' : doctor.warnCount ? 'warning' : 'ok', doctor.passCount + '/' + doctor.totalChecks + ' pass'); renderDoctor(doctor.checks || []);
      text('discovery-count', discoveries.total || 0); renderDiscoveries(discoveries.recent || []); renderCommands(data.commands); renderAdapters(data.adapters);
      text('ideas-count', (ideas.totalPending || 0) + ' pending'); renderIdeas(ideas.pending || []); text('history-count', (history.total || 0) + ' released'); renderHistory(history.items || []);
    }

    let refreshing = false;
    async function refresh() { if (refreshing) return; refreshing = true; try { const response = await fetch('/api/dashboard'); if (!response.ok) throw new Error('HTTP ' + response.status); renderSnapshot(await response.json()); byId('live-dot').classList.add('on'); text('live-label','Connected · live snapshot every 2 seconds'); } catch (error) { byId('live-dot').classList.remove('on'); text('live-label','Disconnected · ' + error.message); } finally { refreshing = false; } }
    refresh(); setInterval(refresh, 2000);
  </script>
</body>
</html>`;

export { DASHBOARD_PAGE_HTML };
