import type { Runner } from "../harness.js";

const PROJECT_PLAN = `# Project Plan

## Product

A tiny uptime monitor that checks one configured URL.

## Users

Developers who want a local availability check.

## Stack

Node.js with no dependencies.
`;

const BUILD_PLAN = `# Build Plan

- [ ] 1. **URL availability check** - accept one configured URL and report whether it is reachable
`;

async function run(t: Runner) {
  t.phase("install into an unborn setup branch");
  t.write(
    "package.json",
    `${JSON.stringify(
      {
        name: "unborn-onboarding-fixture",
        private: true,
        type: "module",
        scripts: { build: "node --check src/app.js" }
      },
      null,
      2
    )}\n`
  );
  t.write("src/app.js", 'console.log("ready");\n');
  t.write(".gitignore", "node_modules/\n");
  t.gitInit();
  t.git("branch", "-m", "feature/devflow-plans");
  t.installDevFlow();

  t.phase("onboard creates the scaffold root and continues");
  const onboarded = t.agent(
    "/onboard\n\nThis repository has no commits. You are approved to create the reviewed scaffold-only initial commit, establish main, return to feature/devflow-plans, and continue onboarding. Use Efficient implementation style, commit DevFlow workflow files, keep the installed Claude adapter, do not add tests or CI, and do not create another commit.",
    { maxTurns: 60 }
  );
  const rootCommit = t.git("rev-list", "--max-parents=0", "HEAD");
  const rootPaths = t.git("show", "--pretty=format:", "--name-only", rootCommit);
  const agentsAfter = t.read("AGENTS.md") || "";

  t.check("Onboard invocation succeeded", onboarded.status === 0);
  t.check("Onboard created exactly one commit", t.git("rev-list", "--count", "HEAD") === "1");
  t.check("the root commit established main", t.git("rev-parse", "main") === rootCommit);
  t.check("the root commit includes the app scaffold", rootPaths.includes("src/app.js"));
  t.check("the root commit excludes DevFlow", !/(?:^|\n)(?:AGENTS\.md|CLAUDE\.md|\.claude\/|\.agents\/|devflow\/)/.test(rootPaths));
  t.check("Onboard returned to the setup branch", t.git("branch", "--show-current") === "feature/devflow-plans");
  t.check("onboarding marker was removed", !agentsAfter.includes("devflow:onboarding-required"));
  t.check("the real build command was recorded", agentsAfter.includes("npm run build"));

  t.phase("overview finalizes the baseline locally");
  t.write("devflow/project-plan.md", PROJECT_PLAN);
  t.write("devflow/build-plan.md", BUILD_PLAN);
  const overview = t.agent(
    "/overview\n\nYou are approved to finalize the reviewed DevFlow baseline locally: create the baseline commit, fast-forward it into main, return to main, and delete feature/devflow-plans. Do not push.",
    { maxTurns: 60 }
  );
  const projectOverview = t.read("devflow/context/project-overview.md") || "";
  const baselinePaths = t.git("show", "--pretty=format:", "--name-only", "HEAD");

  t.check("Overview invocation succeeded", overview.status === 0);
  t.check("Overview generated the planned product context", /uptime monitor/i.test(projectOverview));
  t.check("Overview embedded the source fingerprint", projectOverview.includes("devflow:source-hash") || projectOverview.includes("Generated by scripts/overview.ts") || projectOverview.includes("Living context artifact"));
  t.check("the baseline was committed with the exact message", t.git("log", "-1", "--format=%s") === "chore: establish DevFlow project baseline");
  t.check("the baseline excludes application source", !baselinePaths.includes("src/app.js"));
  t.check("the baseline includes installer metadata", baselinePaths.includes(".nexus/nexus-devflow.json") || baselinePaths.includes("devflow/.state/manifest.json"));
  t.check("the baseline excludes transient activity", !baselinePaths.includes("devflow/.state/run.json"));
  t.check("Overview returned to main", t.git("branch", "--show-current") === "main");
  t.check("the setup branch was deleted", !t.git("branch", "--list", "feature/devflow-plans"));
  t.check("main contains the scaffold and baseline commits", t.git("rev-list", "--count", "main") === "2");
  t.check("the final working tree is clean", !t.git("status", "--porcelain"));
}

export default {
  name: "unborn-onboarding",
  description: "Onboard repairs an unborn repository and Overview finalizes its baseline without manual Git recovery",
  run
};
